[package]
name = "rwalk"
version = "0.2.13"
authors = ["cstef"]
description = "A blazing fast web directory scanner"
license = "MIT"
repository = "https://github.com/cestef/rwalk"
readme = "README.md"
keywords = ["web", "directory", "scanner", "fuzzing", "bruteforce"]
edition = "2021"
exclude = ["assets/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.8", features = ["derive", "env"] }
colored = "2.0.4"
csv = "1.3.0"
dirs = "5.0.1"
dotenv = "0.15.0"
env_logger = "0.10.1"
field_accessor = "0.5.2"
futures = "0.3.29"
indicatif = "0.17.7"
lazy_static = "1.4.0"
log = "0.4.20"
num_cpus = "1.16.0"
parking_lot = { version = "0.12.1", features = ["serde"] }
ptree = "0.4.0"
regex = "1.10.2"
reqwest = "0.11.22"
rustyline = "12.0.0"
serde = { version = "1.0.192", features = ["rc"] }
serde_json = "1.0.108"
sha2 = "0.10.8"
signal-hook = "0.3.17"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
stopwatch = "0.0.7"
tokio = { version = "1.34.0", features = ["full"] }
url = "2.4.1"
