[package]
name = "rwalk"
version = "0.5.17"
authors = ["cstef"]
description = "A blazing fast web directory scanner"
license = "MIT"
repository = "https://github.com/cestef/rwalk"
readme = "README.md"
keywords = ["web", "directory", "scanner", "fuzzing", "bruteforce"]
edition = "2021"
exclude = ["assets/*", ".github/*"]

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.8", features = ["derive", "env", "string"] }
clap-markdown = "0.1.3"
colored = "2.0.4"
csv = "1.3.0"
dirs = "5.0.1"
dotenv = "0.15.0"
env_logger = "0.10.1"
field_accessor_pub = "0.5.3"
futures = "0.3.29"
http-rest-file = "0.5.1"
indicatif = { version = "0.17.7", features = ["improved_unicode"] }
itertools = "0.12.1"
lazy_static = "1.4.0"
log = "0.4.20"
md5 = "0.7.0"
merge = "0.1.0"
num_cpus = "1.16.0"
parking_lot = { version = "0.12.1", features = ["serde"] }
ptree = "0.4.0"
regex = "1.10.2"
reqwest = { version = "0.11.22", default-features = false, features = [
    "native-tls-vendored",
] }
rustyline = "12.0.0"
serde = { version = "1.0.192", features = ["rc"] }
serde_json = "1.0.108"
signal-hook = "0.3.17"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
stopwatch = "0.0.7"
tokio = { version = "1.34.0", features = [
    "io-std",
    "sync",
    "fs",
    "macros",
    "rt-multi-thread",
] }
toml = "0.8.11"
url = "2.4.1"
clap_complete = "4.5.1"
clap_complete_nushell = "4.5.1"

# Strip the debug symbols from the binary
[profile.release]
strip = true
lto = true
codegen-units = 1
