[package]
name = "rwalk"
version = "0.9.0"
authors = ["cstef"]
description = "A blazing fast web directory scanner"
license = "MIT"
repository = "https://github.com/cestef/rwalk"
documentation = "https://rwalk.cstef.dev"
readme = "README.md"
keywords = ["web", "directory", "scanner", "fuzzing", "bruteforce"]
edition = "2021"
exclude = ["assets/*", ".github/*"]

[package.metadata.binstall]
pkg-fmt = "tgz"
[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version }-windows-amd64{ archive-suffix }"
pkg-fmt = "zip"
[package.metadata.binstall.overrides.aarch64-apple-darwin]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version }-darwin-arm64{ archive-suffix }"
[package.metadata.binstall.overrides.x86_64-apple-darwin]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version }-darwin-amd64{ archive-suffix }"
[package.metadata.binstall.overrides.x86_64-unknown-linux-gnu]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version }-linux-amd64{ archive-suffix }"
[package.metadata.binstall.overrides.x86_64-unknown-linux-musl]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version }-linux-amd64{ archive-suffix }"
[package.metadata.binstall.overrides.aarch64-unknown-linux-gnu]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version }-linux-arm64{ archive-suffix }"
[package.metadata.binstall.overrides.aarch64-unknown-linux-musl]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version }-linux-arm64{ archive-suffix }"


[dependencies]
clap = { version = "4.5.4", features = [
    "derive",
    "env",
    "string",
    "cargo",
    "wrap_help",
] }
clap-markdown = "0.1.3"
colored = "2.1.0"
csv = "1.3.0"
dirs = "5.0.1"
env_logger = "0.11.6"
futures = "0.3.30"
http-rest-file = "0.5.1"
indicatif = { version = "0.17.8", features = ["improved_unicode"] }
itertools = "0.14.0"
lazy_static = "1.5.0"
log = "0.4.21"
md5 = "0.7.0"
merge = "0.1.0"
num_cpus = "1.16.0"
parking_lot = { version = "0.12.1", features = ["serde"] }
ptree = "0.5.2"
regex = "1.10.2"
reqwest = { version = "0.12.12", default-features = false, features = [
    "native-tls-vendored",
] }
rustyline = "13.0.0"
serde = { version = "1.0.217", features = ["rc"] }
tokio = { version = "1.37.0", features = [
    "io-std",
    "sync",
    "fs",
    "macros",
    "rt-multi-thread",
    "signal",
] }
toml = "0.8.19"
url = "2.5.0"
clap_complete = "4.5.2"
clap_complete_nushell = "4.5.1"
tabled = { version = "0.17.0", features = ["ansi"] }
strsim = "0.11.1"
scraper = "0.22.0"
serde_json = "1.0.117"
rhai = { version = "1.18.0", features = ["sync", "serde"] }
better-panic = "0.3.0"
color-eyre = "0.6.3"
strip-ansi-escapes = "0.2.0"
human-panic = "2.0.0"
async-trait = "0.1.80"
rand = "0.8.5"

# Strip the debug symbols from the binary
[profile.release]
strip = true
lto = true
codegen-units = 1
