base_url = "https://dev.rwalk.cstef.dev"
minify_html = true
compile_sass = false

build_search_index = true

[search]
index_format = "fuse_javascript"
include_description = true
include_path = true
include_content = true

[markdown]
highlight_code = true
render_emoji = true
bottom_footnotes = true

highlight_theme = "css"
