on:
    release:
        types: [published]
    workflow_dispatch:
name: Homebrew Releaser
jobs:
    homebrew-releaser:
        runs-on: ubuntu-latest
        name: homebrew-releaser
        steps:
            - name: Release my project to my Homebrew tap
              uses: Justintime50/homebrew-releaser@v1
              with:
                  homebrew_owner: cestef
                  homebrew_tap: homebrew-tap
                  formula_folder: formula
                  github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                  commit_owner: homebrew-releaser
                  commit_email: homebrew-releaser@cstef.dev

                  install: 'bin.install "rwalk"'
                  # Adds URL and checksum targets for different OS and architecture pairs. Using this option assumes
                  # a tar archive exists on your GitHub repo with the following URL pattern (this cannot be customized):
                  # https://github.com/{GITHUB_OWNER}/{REPO_NAME}/releases/download/{TAG}/{REPO_NAME}-{VERSION}-{OPERATING_SYSTEM}-{ARCHITECTURE}.tar.gz'
                  # Darwin AMD pre-existing path example: https://github.com/justintime50/myrepo/releases/download/v1.2.0/myrepo-1.2.0-darwin-amd64.tar.gz
                  # Linux ARM pre-existing path example: https://github.com/justintime50/myrepo/releases/download/v1.2.0/myrepo-1.2.0-linux-arm64.tar.gz
                  # Optional - booleans
                  target_darwin_amd64: true
                  target_darwin_arm64: true
                  target_linux_amd64: true
                  target_linux_arm64: true

                  update_readme_table: true

                  # Skips committing the generated formula to a homebrew tap (useful for local testing).
                  skip_commit: false
                  # Logs debugging info to console.
                  debug: false
