on:
    push:
        tags:
            - "v*.*.*"
    workflow_dispatch:

name: Publish
env:
    CARGO_TERM_COLOR: always
jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2
            - uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            - name: Install stable toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
            - run: |
                  cargo run -- --generate-markdown > HELP.md
                  cp HELP.md docs/pages/options.md
                  git add HELP.md docs/pages/options.md
                  git config --global user.email "action@github.run"
                  git config --global user.name "GitHub Action"
                  git commit -m "Update HELP.md" || true
                  git pull origin main --rebase
                  git push origin HEAD:refs/heads/main
            - run: cargo publish --token ${{ secrets.CRATES_TOKEN }} --no-verify
