on:
    push:
        tags:
            - "v*.*.*"
    workflow_dispatch:

name: Publish
env:
    CARGO_TERM_COLOR: always
jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2
            - name: Rust Cache
              uses: Swatinem/rust-cache@v2.7.3
            - name: Install stable toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
            - run: cargo run -- --generate-markdown > HELP.md
            - run: cargo run -- --generate-completions
            - run: git add HELP.md completions/*
            - run: git config --global user.email "action@github.run"
            - run: git config --global user.name "GitHub Action"
            - run: git commit -m "Update HELP.md and completions"
            - run: git pull origin main --rebase
            - run: git push origin HEAD:refs/heads/main

            - run: cargo publish --token ${CRATES_TOKEN}
              env:
                  CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
