on:
    push:
        branches:
            - dev

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - uses: taiki-e/install-action@nextest

            - run: cargo nextest run
              env:
                  CARGO_TERM_COLOR: always
